"""add catalogue and attempt tables

Revision ID: 3cffc29f70fc
Revises: 3b171da54171
Create Date: 2026-08-24 21:13:09.917672

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3cffc29f70fc'
down_revision: str | None = '3b171da54171'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('pronouns', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=False),
    sa.Column('avatar', sa.String(length=32), nullable=False),
    sa.Column('chief_complaint', sa.String(length=200), nullable=False),
    sa.Column('opening_line', sa.Text(), nullable=False),
    sa.Column('deflections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impatient_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jargon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('follow_ups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_slug'), 'patients', ['slug'], unique=True)
    op.create_table('patient_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('revealed_at_start', sa.Boolean(), nullable=False),
    sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patient_line', sa.Text(), nullable=False),
    sa.Column('credits', sa.String(length=32), nullable=False),
    sa.Column('safety_critical', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_facts_patient_id'), 'patient_facts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_facts_slug'), 'patient_facts', ['slug'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('setting', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('duration_max', sa.Integer(), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_slug'), 'scenarios', ['slug'], unique=True)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'in-progress'"), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('revealed_fact_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('objectives_met', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('recommendation_choice', sa.String(length=64), nullable=True),
    sa.Column('recommendation_reasoning', sa.Text(), nullable=True),
    sa.Column('counseling', sa.Text(), nullable=True),
    sa.Column('referral_choice', sa.String(length=64), nullable=True),
    sa.Column('referral_reasoning', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_scenario_id'), 'attempts', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missed', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('safety_issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('better_approach', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('next_scenario_slug', sa.String(length=64), nullable=False),
    sa.Column('next_scenario_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_attempt_id'), 'evaluations', ['attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_attempt_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_scenario_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_scenarios_slug'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_patient_facts_slug'), table_name='patient_facts')
    op.drop_index(op.f('ix_patient_facts_patient_id'), table_name='patient_facts')
    op.drop_table('patient_facts')
    op.drop_index(op.f('ix_patients_slug'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
